---
abstract: 'Perl interface to the 3.x series of the gtk+ toolkit'
author:
  - 'Torsten Schoenfeld <kaffeetisch@gmx.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk3
requires:
  Glib: 1.240
  Glib::Object::Introspection: 0.002
version: 0.003
