---
abstract: 'Perl interface to the 3.x series of the gtk+ toolkit'
author:
  - 'Torsten Schoenfeld <kaffeetisch@gmx.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk3
requires:
  Cairo::GObject: 1.000
  Carp: 0
  Exporter: 0
  Glib::Object::Introspection: 0.014
version: 0.009
